### ISSUE TITLE
[Imagens] Área disponível para download muito ampla

### ISSUE THREAD

**Issue by TabataPohren** [francielekreff/ndvi#2]
A imagem disponível para download possuía uma área muito maior que a região selecionada.
(120 km)

**Comment by TabataPohren** [comment]
Localiza a região selecionada, dentro da área ampla da cobertura pela imagem de satélite.

**Comment by TabataPohren** [comment]
Realizar o download da melhor imagem disponível.

**Comment by TabataPohren** [comment]
Aplicar técnica de pré-processamento de  imagens: rotação e recorte.

**Comment by francielekreff** [comment]
As issues #3 e #4  foram criadas para a implementação das técnicas de pré-processamento de rotação e recorte, respectivamente.

**Comment by francielekreff** [comment]
As issues #3 e #4 foram criadas para a implementação das técnicas de pré-processamento de rotação e recorte, respectivamente.
